language: python
os:
- linux
python:
- '3.6'
install:
- pip install .
- pip install pytest
script: pytest
deploy:
  provider: pypi
  user: alejoe91
  on:
    branch: master
    tags: true
  password:
    secure: ERtYITdo6D1pLQJlYFNO/Tw5OAKjODEReOcnvMf3y+Y66czgg/91JiMyRQTaUkC1eG8rpUTh0+sgWL1m2TDkc9ORekDUbOGbyTzqVJpD3YrMSQ89j2IvGS7kBiHTzQW0QTG8TCfyxr3ULYDLzQn/dO/igaEF/vOLQKX7eEDUqhdhvgi90m3tPlUVlOj8b0FOpnXG3HuaEVaei7xE66fxAW0rN/dVPMRgPsd35pszCEs4OyL+xaaN3xfm+Yl/E/efdHSl05UiUFiiLIfq737NKsWBluVW+cVuuLH5kwtPzqQkF6N71mLgCH8HPy/MszMkm8S+SeKnUWVRGP06K+Pl78ZK46laGI/zKArdejPbadCJoBTrSJEr8JZ2jA64QStYiLzktfv+Y6MbHBT2BG/6xWnFvufeqSZbmrXkWdyLi+weXtP0ih+jtCXpmVoAhQvHCuoJziGFNu8BRSNm77KK1RTc7QhxoGOIHiS51eM/1Wadac5DP2LQF/rNaB6PkhPiMwyDAYSeOKQxWR93qM4UQ0FQf2Ap8C9iQDlpbHYaExKJfiwC1eioZdCLsTdn7MEm5t8OBAxXGr4+f7sGIAHDF/eUTnoT82UsxE1905R1DqOmWceblUM2tGK/R4tP/bS14WIzeCWLn65Pdnkd0qWXT2aT7eQ2GbVW8+MSzAM7MTA=
