language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: enabled
install:
- pip install .
- pip install pytest
script: pytest
deploy:
  provider: pypi
  user: alejoe91
  on:
    tags: true