# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test and Upload Python Package

on:
  push:
    tags:
       - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Which python
        run: |
          which python
      - name: Install dependencies
        run: |
          pip install .
          pip install setuptools wheel twine build
          pip install pytest
      - name: Test with pytest and build coverage report
        run: |
          pytest
      - name: Package and Upload
        env:
          STACKMANAGER_VERSION: ${{ github.event.release.tag_name }}
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build --sdist --wheel
          twine upload dist/*
