name: Python Package using Conda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Test on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"] # skip macos-latest; https://github.com/s-weigand/setup-conda/issues/432
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.8
      - name: Which python
        run: |
          conda --version
          which python
      - name: Install dependencies
        run: |
          pip install .
          pip install pytest
      - name: Test with pytest and build coverage report
        run: |
          pytest
